name: duanju_app
description: 独立运行的短剧应用
publish_to: none
version: 0.2.103+5

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  ffi: ^2.2.0
  media_kit: 1.2.6
  media_kit_video: 2.0.1
  media_kit_libs_video: ^1.0.7
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: 2.5.3
  shared_preferences_platform_interface: 2.4.1
  flutter_foreground_task: 9.2.2
  file_picker: 11.0.3
  crypto: ^3.0.7
  window_manager: ^0.5.1
  nsd: 5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/video_enhancement/
